import { InvoiceRow } from './types';

export const invoicesData: InvoiceRow[] = [
  {
    id: 'inv-82',
    status: 'Concept',
    jaarcode: null,
    code: 82,
    project: '-',
    offerte: { label: 'Nieuw' },
    volledigBetaald: false,
    totaalExcl: 5.63,
    totaalIncl: 5.63,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: '-',
    contactName: 'test support',
    emailAddress: '-',
    emailIndicators: 0,
    sentIndicator: true,
    reference: '-',
    paymentTermDays: 14,
    createdAt: '21–11–2025 11:54',
    createdBy: { kind: 'Systeem', initials: 'S', name: 'Systeem' },
    updatedAt: '06–01–2026 11:34',
    updatedBy: { kind: 'Gebruiker', initials: 'P', name: 'Patrick Boesveld' },
  },
  {
    id: 'inv-81',
    status: 'Concept',
    jaarcode: null,
    code: 81,
    project: '-',
    offerte: null,
    volledigBetaald: false,
    totaalExcl: 65,
    totaalIncl: 78.65,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'Centrada',
    contactName: 'M. Gabriel',
    emailAddress: '-',
    emailIndicators: 2,
    sentIndicator: true,
    reference: 'OV-2510765',
    paymentTermDays: 14,
    createdAt: '24–07–2025 15:34',
    createdBy: { kind: 'Gebruiker', initials: 'S', name: 'Sven | Installatiegroep' },
    updatedAt: '24–07–2025 16:26',
    updatedBy: { kind: 'Gebruiker', initials: 'L', name: 'Lars Albrechts' },
  },
  {
    id: 'inv-80',
    status: 'Concept',
    jaarcode: null,
    code: 80,
    project: '-',
    offerte: null,
    volledigBetaald: false,
    totaalExcl: 65,
    totaalIncl: 78.65,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'OpusFlow',
    contactName: '-',
    emailAddress: '-',
    emailIndicators: 2,
    sentIndicator: true,
    reference: 'OV-TEST',
    paymentTermDays: 14,
    createdAt: '24–07–2025 14:17',
    createdBy: { kind: 'Gebruiker', initials: 'L', name: 'Lars Albrechts' },
    updatedAt: '24–07–2025 16:03',
    updatedBy: { kind: 'Gebruiker', initials: 'L', name: 'Lars Albrechts' },
  },
  {
    id: 'inv-79',
    status: 'Concept',
    jaarcode: null,
    code: 79,
    project: 'naam',
    offerte: null,
    volledigBetaald: false,
    totaalExcl: 2000,
    totaalIncl: 2119.7,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'Centrada',
    contactName: 'M. Gabriel',
    emailAddress: '-',
    emailIndicators: 2,
    sentIndicator: true,
    reference: '-',
    paymentTermDays: 14,
    createdAt: '27–06–2025 11:00',
    createdBy: { kind: 'Systeem', initials: 'S', name: 'Systeem' },
    updatedAt: '27–06–2025 11:02',
    updatedBy: { kind: 'Gebruiker', initials: 'S', name: 'Sven | Installatiegroep' },
  },
  {
    id: 'inv-78',
    status: 'Goedgekeurd',
    jaarcode: null,
    code: 78,
    project: 'naam',
    offerte: null,
    volledigBetaald: false,
    totaalExcl: 960,
    totaalIncl: 960,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'Centrada',
    contactName: 'M. Gabriel',
    emailAddress: '-',
    emailIndicators: 2,
    sentIndicator: true,
    reference: '-',
    paymentTermDays: 14,
    createdAt: '10–06–2025 15:11',
    createdBy: { kind: 'Systeem', initials: 'S', name: 'Systeem' },
    updatedAt: '10–06–2025 15:12',
    updatedBy: { kind: 'Gebruiker', initials: 'L', name: 'Lars Albrechts' },
  },
];
