import { InvoiceRow } from './types';

export const invoicesData: InvoiceRow[] = [
  {
    id: 'inv-82',
    jaarcode: null,
    code: 82,
    status: 'Concept',
    project: '-',
    offerte: { label: 'Nieuw' },
    volledigBetaald: false,
    totaalExcl: 5.63,
    totaalIncl: 5.63,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: '-',
  },
  {
    id: 'inv-81',
    jaarcode: null,
    code: 81,
    status: 'Concept',
    project: '-',
    offerte: null,
    volledigBetaald: false,
    totaalExcl: 65,
    totaalIncl: 78.65,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'Centrada',
  },
  {
    id: 'inv-80',
    jaarcode: null,
    code: 80,
    status: 'Concept',
    project: '-',
    offerte: null,
    volledigBetaald: false,
    totaalExcl: 65,
    totaalIncl: 78.65,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'OpusFlow',
  },
  {
    id: 'inv-79',
    jaarcode: null,
    code: 79,
    status: 'Concept',
    project: '-',
    offerte: { label: 'naam' },
    volledigBetaald: false,
    totaalExcl: 2000,
    totaalIncl: 2119.7,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'Centrada',
  },
  {
    id: 'inv-78',
    jaarcode: null,
    code: 78,
    status: 'Goedgekeurd',
    project: '-',
    offerte: { label: 'naam' },
    volledigBetaald: false,
    totaalExcl: 960,
    totaalIncl: 960,
    totaalBetaald: 0,
    totaalVoorschot: 0,
    kredietOorspr: '-',
    bedrijfsnaam: 'Centrada',
  },
];

